// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WorkloadsDb.Model
{
    public partial class Assignment
    {
        public Assignment()
        {
            Workloads = new HashSet<Workload>();
        }

        public int AssignmentId { get; set; }
        public string Customername { get; set; }
        public string Description { get; set; }
        public string Contact { get; set; }

        public virtual ICollection<Workload> Workloads { get; set; }
    }
}